version: "3.9"

services:
  telemeter:
    build:
      context: ./telemeter
      dockerfile: dockerfile
    container_name: watcher-dev
    networks:
      - smartops-network

  detector:
    build:
      context: ./agent-service/
      dockerfile: agents/detector/Dockerfile
    container_name: smartops-detector
    ports:
      - "8001:8001"
    networks:
      - smartops-network

  rca:
    build:
      context: ./agent-service
      dockerfile: agents/rca_brain/Dockerfile
    container_name: smartops-rca
    ports:
      - "8002:8002"
    env_file:
      - agent-service/.env
    networks:
      - smartops-network

  orchestrator:
    build:
      context: ./agent-service/
      dockerfile: agents/orchestrator/Dockerfile
    container_name: smartops-orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - detector
      - rca
    networks:
      - smartops-network

  observer:
    build:
      context: ./observer
      dockerfile: dockerfile
    container_name: observer
    ports:
      - "80:80"
    networks:
      - smartops-network
    depends_on:
      - orchestrator

networks:
  smartops-network:
    driver: bridge
